OPENAI_API_BASE: https://api.groq.com/openai/v1
OPENAI_API_KEY: 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

MODEL_NAME: "llama3-70b-8192"
RESOURCES_SUMMARY_MODEL_NAME: "llama3-70b-8192"

#QDRANT_PORT: 6333
#QDRANT_HOST_NAME: http://172.17.0.2